hash-format = "sha256"

[[files]]
file = "config/debugify.json"
hash = "ec45639f6f7a9577b271004d5ca655ba9dce9b70c8de1e3087f94fb0ca9c95d6"

[[files]]
file = "config/enchancement.json"
hash = "cf7f857b1fd0174e616502b447d07dce9a08a0a9194e6de6f565061c7da8356a"

[[files]]
file = "config/spellbound.json"
hash = "32603c40aa93652ee7725724f8fd06d06393608b0c3e2de9912224ad03bcea15"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "b0e11760190870b23a50e68018a3792e6ad3929302bb2917db21268a20f858af"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "c869b1e1cf73b7b0d5ca03e4657fdbed845d85ab5aca0449248fd144545ecfb7"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "d1263f28704a153ad67c648fe20b37ab8c9d65f279b2130d29a4ce8be8ad9d0a"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "b2caa9c1a2ff986d6f1816371c44989ffc7c0336f91475b9a6fcdc61fae9ef40"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "d5d39233d392afb000aa2c6c4eba69a0cf65d0db28879fc90777a9bc90341693"

[[files]]
file = "config/yosbr/config/inspecio.json"
hash = "3ea7cea3ac8af927933266fb631677c96098f95bae61f2e5e23d6512a66634a2"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "a9a6c0ecd319c9417e35b3b17f91de37075001803296dc6fab2a52f888a342c8"

[[files]]
file = "config/yosbr/config/playerex.json"
hash = "a05cf4237bca33782aa99e7ee7d777498433a9a8b3b0eddc235ce5d19fd9ded1"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "6d9d65b9e92519e09931488219a9cb618e67bde4faf06c192e6243f3dcbc09fd"

[[files]]
file = "config/yosbr/config/quickconnectbutton.json5"
hash = "5cf674740d167ad1af57049b3b6cacfe085a8e700a44d13ee997771aa2996453"

[[files]]
file = "config/yosbr/config/relicex.json"
hash = "799f4453140ac13834c46749c9a5e413acaea5b6679c2bed8e132ab902f0a65f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "b41ffcbb5a3a65c822c3031ae1721ee445f64c46e4796298030342875d34038e"

[[files]]
file = "config/yosbr/config/styled-chat.json"
hash = "b3275844007bc4b70eeaad61acf3b26ff69983eb87ff81f4ff52b0043f48ef07"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "accf3ae12dbb30c807b81d59a5310784aef56bb992cbd287fd6117aaf144fcff"

[[files]]
file = "config/yosbr/options.txt"
hash = "bb1064d7059d74f36f6b67f71457b1633d1fe1cfa7d69f1b15bc9770abb30e06"

[[files]]
file = "mods/animatica.pw.toml"
hash = "8f19c60f966d1147794ebfe40b88c9caf37ba464d8457fc5a59d69fa2cb7f564"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "f0e9dfb7405e8c7667a670f398a644ec17ac044dd5404ebe9cbf5aa5bfb907c4"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "808c30194a90fce3a57ba82e92333518f3a14a5fdb69c84b5fac247e46557632"
metafile = true

[[files]]
file = "mods/armored-elytra.pw.toml"
hash = "b46af2de1693fcaf892fd6dd1734915a9a36549093144b724e940cce5936e17c"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "4f64efbeb252e3b600aaf5d58e4a7db02790dd9d3609595f7ede779b988862ab"
metafile = true

[[files]]
file = "mods/backpackmod.pw.toml"
hash = "6a521e6df498ca624215a76e8423961b28f9cd6c1124c8798ea7a78842244606"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "63edbd012db544d0590a1cd2563a4973c0316b8033370b41a48c05b0e8e667e5"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "7c5c3e69f7d2abcde972efc46603be697818d834f28e94bbdb4fd5ee565c1c9a"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
hash = "dbbe09e6693b3c8608f7831b99f66ff57a62a5dfef612295cbe144553abd7336"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
hash = "e7d7b42cc3b56d79d18599f936742b711f849b372ca4b6106a5d00d624573d59"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
hash = "f260530e165404ac8ca8baf8530038bebc74101ace0cfc48e41cc0f1f0a40c1b"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "c19d5ad0b3b30fc4d9f1a712b0686f267bbd08b825e5439817b585195f7d0797"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "1df518e27d1648ff8c950c14a7ce4e72d10955ddf08331169a723305d45b4661"
metafile = true

[[files]]
file = "mods/bosses-of-mass-destruction.pw.toml"
hash = "c5fe06b7d389fa87dadca4f4974660eff26b336a908ee506fd616f717e1be581"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "fd3bd8c3ff7d0fd1abe9919227c724eb59df1e25b2ee6ba2c9cdb84408542e34"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "5d898bbdb655828c59223382f85016f8328884b3ff176b697c51e8dedaec68c1"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "6e8faa4779dca8bafd4cc91cad8f7fe425f6d3d08511463466c6c13b8ffa55dd"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "4b9046c17c02c1a35f6fe2747bdb74d219f3b9b02a2e8fdc9c1dfc5008f7c422"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b52cd1f4295d855882a41b5f164385e2ba460d7766a2e2e6183ef56c00c824ab"
metafile = true

[[files]]
file = "mods/cleancut.pw.toml"
hash = "7ea37e2cbe755149aaaf569fd9999541fc766c6057fc7a062a715af51b387b93"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "6b20375222bb3b3e42928a5a7d9f678c5d50a12600abe281fd92f36331666687"
metafile = true

[[files]]
file = "mods/colytra-fabric.pw.toml"
hash = "cbd4dae78290f64154c27b046abe13eab7cb46108bd267bc01ae8dbe8f9658ea"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "c6ada8bbe7f1e2e19bdf882bc0ad625435b9305e3dde5e09f33b991ff0d43da1"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "19783c9eb3f9c3a9522f47f11fa9b87dd62b64a42e52cadbdf9ce9d5c8d73d46"
metafile = true

[[files]]
file = "mods/data-attributes.pw.toml"
hash = "9d272daefdc59f0a52348c7c5c7660541316b61b0c9f795abe741c692af5dda8"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "3c2b9753af947a22db085b3a7c0ea6e8a2eef4aeed9540a1cae44e774cf83c3b"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "783c0415795fc4bea6d85315aac54d3a3f2770fcd02d66dad1f626b311f8bf4f"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "dd0e913b88ea98ebd3c986af171706b3cb8502a37271b3b4a39744071029a54d"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "f52293cc81b07666eeee3bfcf5f34039e2d2bc64cd22416b5cbdb554eec17a0e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "5b2566cd4cdfb5b47c31246af31ee4e27ec8ace3b248a00823adec7efd8f8fed"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "8b3a9779801e8404de468697b63cc171beab18610fdcfdb46f6709b9b677b689"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "df887ef39e3a78cf9a23adb5667978e7bb0ae2d3f7db68b670489180a8e2bc05"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "bdb2354f0d8ec021366bab0dbc07d4691d9b41fc825d95899d879aeeeb717107"
metafile = true

[[files]]
file = "mods/extra-origins.pw.toml"
hash = "186987bc3f451d929e42bab5dc391ca07a6badd7ade2c3ac7c4b6a291d6f44b5"
metafile = true

[[files]]
file = "mods/extrasounds.pw.toml"
hash = "2e871ee3068cfb44e799d244f4e586e6f32e5708b16a6832939c3c4f01d91170"
metafile = true

[[files]]
file = "mods/ezrstorage.pw.toml"
hash = "b453a280fcd953cf3b0a92145417aa8b3e6ef3b20641a310965c887bddfe1b8c"
metafile = true

[[files]]
file = "mods/fabric-rep-system.pw.toml"
hash = "c0617e1dd8e9a9269e2703ecea0bdc925bd9ae13dff83006122ddd4617265caa"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "fa5844242239c7228674022960e1506d19b062aa056ead17d5d52f1f9d5e6a57"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "6ac3d99d1f4d274bb13d92e36538f4c108b6e2f0ede7835d5f8340f2bb04d46c"
metafile = true

[[files]]
file = "mods/fastback.pw.toml"
hash = "83cdaa833826cfdf0cfd0b41637899d534da478ce9545c704f1bb298336a69cb"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "00960cdd63d16c9a2ca9f1e3a9c3aa79d789c0284fb19091ba4b8841a7f5def5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "63abc798591351fddc8069cf92991ffe6e058f939e259a27d284270e835e9530"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
hash = "977ca09ec10461c0ca552cfbbe95a5e6e6c39554cb42cdbea4c2f110b41d04a5"
metafile = true

[[files]]
file = "mods/gate-of-babylon-1.7.0-1.19.2.jar"
hash = "4c383c30ac21474a10a35ad13dfc49ed8f118d1e075998bec4d99818f127585b"

[[files]]
file = "mods/geckolib.pw.toml"
hash = "c04bd6360ba1f3a7fbf85926cdb7ea052b7da0e57e47e3220a772817e93a36e9"
metafile = true

[[files]]
file = "mods/gravity-api.pw.toml"
hash = "0a7b9b0b4da2593a122a078d751b9bda13f053e28ace26758ff87b81afd56da3"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "53e83e4a46fa1fc9f865fc1dd458b256f3f3083cdeabdee417834d83e3b1b739"
metafile = true

[[files]]
file = "mods/immersive-weathering.pw.toml"
hash = "9233d882e4c914db72499731aecd18de2c2b0099f9c73f54228e424a7cd3b3e3"
metafile = true

[[files]]
file = "mods/impaled.pw.toml"
hash = "717e42c31fd9e80097f4d21ed6c138094a0025b53dfcf14d780c0078eb1b8722"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "7417e0de6b62543ad4c7b8f4da4970f9fc67beb9d21831bb397f93b89b77763d"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "7cfacba402f52a71096bda72ede806b9b6964c2c807019da76f4e27fa839c8a5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3f052faaaa0d0caafe0e66129940fcd580cd0252791c47e3b3c451571f6c77d8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "353698e0ad3f1f1f8ae2819ebeaac830b461f5c92fb3c6fdde7cf66d05693d63"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "ce512c2c230261ec8146b07f05a33b21c90006752f111134163834936dd67aba"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/literal-sky-block-fabric.pw.toml"
hash = "d69196ced8829617dd2b7315b946f926c019a8fdb0fd558928396b4e0e5fedab"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "77e9a02e09ec5a0d6682e5f448953048d99e36da299d92627044aff0828798e3"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "10adb8c5a5aab921443515680dd58a1369e1209ec4966fde0759d64f777f7525"
metafile = true

[[files]]
file = "mods/mclogs.pw.toml"
hash = "04cc7576acd1459ab9b1df3b143106f44ae9c5df3679769038ca83390c5f4fd5"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/mermod-fabric.pw.toml"
hash = "b4e6e6966ab253aaa1a89d383aa118888f5838252aba7c0efac08986ef1db941"
metafile = true

[[files]]
file = "mods/mine11lib.pw.toml"
hash = "23ffaad81611e265dcc8472290d5d7a89c2e1d2622b0330d75556a32e67c0b04"
metafile = true

[[files]]
file = "mods/mob-hat.pw.toml"
hash = "a20b14129f4a0ea0a2be6b378e6bdb003dd55556c516f78d0dd24bb2d9edc89d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "09eb7db3ca7778d91ad66845e41b6b4814655fe375a05d4a69528c74b4f1c8af"
metafile = true

[[files]]
file = "mods/modrinth-smp-1.0-SNAPSHOT.jar"
hash = "fde5ff175bcae37d0b5bc293c9a0c8a57db03ce26f3ddb0a7e4118addff26c25"

[[files]]
file = "mods/moonlight.pw.toml"
hash = "eb6ad65bc55853f87bbd72085e690fd914318b94e3108bb6583b8da4363f480b"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "1191c0ed4c2be46db9814885dc1beb33d22a2175758ad0af8a5a53afe851d7c6"
metafile = true

[[files]]
file = "mods/niceload.pw.toml"
hash = "c90bf0b815b1e8ee151e531838d0b435005cd35485fb6dc6017e6136f6a40930"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "17dc4f0920a4089790c8d13abff319a5e83f2aea7a06cdd3cc79699fa5ccdc8a"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "862b429a623762ef0469eb2a409b9450a9b70071cf9bffabca654b97f7528424"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "d6a99e144be13fb3d0865925bf73357a2ff82f4114929cc2f35930eb21f3c7e9"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "2dab4b3cea2f1ce1505c3c7be55d8fb6123a7593435134f2c15eed18e6c07ddf"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "03d4272f909720df400b6af4c90a93fc95e3a55c85935e7777724ba9f9bcb994"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "bfb2ed4cb4f501621eab3467dc6c6206525a414d0fe401a8f91f8aaca7232993"
metafile = true

[[files]]
file = "mods/playerex.pw.toml"
hash = "2632c2ce766ff44a8ed45a10239a6435ca10031b3a885d34f6c326d172e7dca8"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "d44a47592608a2ef6eb105eb6a4642839e1a9ea59736b92345c0fa492ddbc47a"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "02afa656e08ce408c1b541e60d9126b8bac35b55a26950547291ee8f54c1899d"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "78fe291bc3d50234209d5b80735b469044f4d858dc8d3ba5bc38d1e098cb786f"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "b39a29623977769f92afcebfdcfa95d71acb2d513b4611a9462c0964b2f30294"
metafile = true

[[files]]
file = "mods/quickconnectbutton.pw.toml"
hash = "62f6af6480f713e7f643c367a157597b3740f0fc3b9d4234adb391ecab236aaa"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
hash = "77aa1af076bfb1175a407037a2d1db80437bae5193db45a557f5f32b3cc4a67f"
metafile = true

[[files]]
file = "mods/rainglow.pw.toml"
hash = "4e8d1c0e827fb476123ca710fcdfcca5649e5ab141e4096d7a066f9b89d7d893"
metafile = true

[[files]]
file = "mods/rats-mischief.pw.toml"
hash = "b0da1f56d9d037a5edb8b837bbf5a7dafb7679f42a9a2bd7865bbb2d4fad57b1"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "400adf83e9c2e73eeb2c71807f18d631b0655852e910cd0f6ff437424e52b1bb"
metafile = true

[[files]]
file = "mods/relicex.pw.toml"
hash = "c856e48744e4db9e1c4861bc32d46b5326b946205aac0f583d169e7548e84a5c"
metafile = true

[[files]]
file = "mods/servertick.pw.toml"
hash = "4ad1f4d5630879670b010035610eb35e8fb3eec45b1d908f6a68b4a91ecbe843"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "3d0f720430c5925f34d52ee314d6e273a10e1c65205b7c10c1118ff7db2964f4"
metafile = true

[[files]]
file = "mods/sizeshiftingpotions.pw.toml"
hash = "4089b257b2607198601115860626d595f72bd5a4faada9ae2606b9e981bcbb2c"
metafile = true

[[files]]
file = "mods/sleep-warp.pw.toml"
hash = "320c6865e322a7d6d8ec60bd2189132c52ee973af10ed255a8aac7cc26ae170e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "e74096c547dbdcdb5ea22d75c60e5f3a526f8226026e5d6b99f3a97aeb9d1214"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "08d9f157fea976ba8e7a20ebfce995fe5419ebddf581fcdab079aaceb33053e3"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "413ce716e1ce679ff1097f1732023a5457ef5ec7b512d247ef087aeefd82d19b"
metafile = true

[[files]]
file = "mods/spellbound-enchantments.pw.toml"
hash = "7a2b44ca2599273ab495832725c4fa3dbed0e08faac97c6cad5a4da5c6c461d1"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "b54a2d0cdb07a011d353462037ee68dfa2108767be8485c58f65fea4986cb934"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "d8811e747723a11a540557e9d602fe16fbbd55fdeb120342f008108f89e8226b"
metafile = true

[[files]]
file = "mods/things.pw.toml"
hash = "6b056c1e695fd8d088c8a373e071953815d7b52fe1087baa44565d3093b111e1"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "b6d4b85f76ab7c63f30c6c2f12f3188c34b7e3977c092cc7062b2902319e3ed2"
metafile = true

[[files]]
file = "mods/towers-of-the-wild-additions.pw.toml"
hash = "916a6b442bad08a86df1069d941000da110b5b24e64fa75ad45c961590cfd7b9"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "b3acdba79cfef7e53cfd4df8dd6e7cbbe4eeae75972bf65fa2a6aaef034f4b8e"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "7469851e3fed3e9176d431c4da39acb4d0d815f0f1e2341d8621d6c96294a697"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "13edb6ded702c85072a99ebe5f36de5d36522a50c1360e01c2a88d2d46a6616f"
metafile = true

[[files]]
file = "mods/woof.pw.toml"
hash = "bd911594a5835278b11c0a0c68cb2145b153ec9a726982a0d10407f75431bad4"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "719da66ac6adbf00ace4a021f1bfcd6aca271b16caa40629de9e73a79b844905"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
hash = "9e86144c0543f6bcfa735d71451e93d3b101c94bd7956079c080e9e2a4f90f60"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "b003caafe717cbbf9ba2a7539bdd361e4d7e58e0d9602bd81a41387691b7e70c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "a50adf5dc08750b87e7681fb99637e39660e61befc795793023f4024ec7eeec3"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "dcfc9996df859731e571721ffef8006ade14f3c2a2f26c716beca15575eb3ce6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d6126b71de887bf0b23a4a064b5f9ebb2f4848533f3b098703c3917ba63e5c69"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "455bd61468b04ec66000901d5c112a97dabd3343f9e6d96ad3c148726e7c5bf8"
metafile = true
